game:
    second_human: False # Instead of the RL play with a second human
    # position of the goal on the board
    goal: "left_down" # "left_down" "left_up" "right_down"
    discrete: True

Experiment:
  loop: max_episodes # Test loop

  max_episodes_mode:
    max_episodes: 70  # max training episodes
    max_duration: 40  # max timesteps in one episode
    action_duration: 0.2
